# Generated by Django 5.2.17 on 2026-10-02 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('BROCHURE', 'Brochure'), ('VIDEO', 'Video'), ('AD', 'Ad Banner')], max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='tools/marketing/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('resolution', models.CharField(blank=True, default='', max_length=20)),
                ('format', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['material_type'], name='dms_tools_m_materia_5661ee_idx'), models.Index(fields=['-created_at'], name='dms_tools_m_created_31d2fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimerCalculation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_calculations', to='dms_sales.confirmedsite')),
            ],
            options={
                'indexes': [models.Index(fields=['unit_id', 'site_id'], name='dms_tools_t_unit_id_4687aa_idx'), models.Index(fields=['unit_id', '-created_at'], name='dms_tools_t_unit_id_708517_idx')],
            },
        ),
    ]
