# Generated by Django 5.2.17 on 2026-10-03 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('app', models.CharField(choices=[('admin', 'Administration'), ('dms', 'DMS'), ('crm', 'CRM'), ('ecommerce', 'E-commerce')], max_length=20)),
                ('level', models.CharField(choices=[('org', 'Organisation'), ('unit', 'Dealership')], max_length=10)),
                ('summary', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['app', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('app', models.CharField(choices=[('admin', 'Administration'), ('dms', 'DMS'), ('crm', 'CRM'), ('ecommerce', 'E-commerce')], max_length=20)),
                ('module', models.CharField(help_text='Which module this makes visible: sales, service, users, dealers...', max_length=40)),
                ('group', models.CharField(help_text='Display grouping: "Enquiries".', max_length=60)),
                ('label', models.CharField(help_text='What it lets you do: "Create an enquiry".', max_length=120)),
            ],
            options={
                'ordering': ['app', 'module', 'group', 'code'],
                'indexes': [models.Index(fields=['app', 'module'], name='permissions_app_10382e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='permissions.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='permissions.RolePermission', to='permissions.permission'),
        ),
        migrations.CreateModel(
            name='AppAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(choices=[('admin', 'Administration'), ('dms', 'DMS'), ('crm', 'CRM'), ('ecommerce', 'E-commerce')], max_length=20)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_access', to='organizations.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='permissions.role')),
            ],
            options={
                'verbose_name_plural': 'app access',
                'constraints': [models.UniqueConstraint(fields=('membership', 'app'), name='appaccess_unique_membership_app'), models.CheckConstraint(condition=models.Q(('app', 'admin'), _negated=True), name='appaccess_never_administration')],
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='rolepermission_unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('app', 'code'), name='role_unique_app_code'),
        ),
    ]
