# Generated by Django 5.2.17 on 2026-10-04 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('spent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(blank=True, help_text='The organization this code founded. Set when the code is spent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_code', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('organization__isnull', True), ('spent_at__isnull', False), _connector='OR'), name='activationcode_attached_implies_spent')],
            },
        ),
    ]
