# Generated by Django 5.2.17 on 2026-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, editable=False, help_text="When this organization's database was created and migrated.", null=True),
        ),
    ]
