# Generated by Django 5.2.17 on 2026-10-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_provisioned_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unit_unique_org_name'),
        ),
    ]
