# Generated by Django 5.2.17 on 2026-10-02 15:18

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=50)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('oc_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=15)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecommerce_orders', to='dms_sales.customer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_orders', to='dms_sales.confirmedsite')),
            ],
        ),
        migrations.CreateModel(
            name='EcommerceOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), output_field=models.DecimalField(decimal_places=2, max_digits=14))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dms_ecommerce.ecommerceorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_order_items', to='dms_sales.productcatalog')),
            ],
        ),
        migrations.AddIndex(
            model_name='ecommerceorder',
            index=models.Index(fields=['unit_id', 'status'], name='dms_ecommer_unit_id_a180ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceorder',
            index=models.Index(fields=['unit_id', '-placed_at'], name='dms_ecommer_unit_id_21166f_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceorder',
            index=models.Index(fields=['unit_id', 'site_id'], name='dms_ecommer_unit_id_4bf4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='ecommerceorderitem',
            index=models.Index(fields=['unit_id', 'order_id'], name='dms_ecommer_unit_id_030cec_idx'),
        ),
    ]
