# Generated by Django 5.2.17 on 2026-10-02 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('requester_user_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
            ],
            options={
                'indexes': [models.Index(fields=['unit_id', 'status'], name='dms_tech_su_unit_id_7dec6b_idx'), models.Index(fields=['unit_id', '-created_at'], name='dms_tech_su_unit_id_e7da3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachineVideo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='tech_support/videos/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('resolution', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='dms_tech_su_categor_640704_idx'), models.Index(fields=['-created_at'], name='dms_tech_su_created_c18a29_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='tech_support/manuals/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='dms_tech_su_categor_50da0a_idx'), models.Index(fields=['-created_at'], name='dms_tech_su_created_7c1500_idx')],
            },
        ),
    ]
