# Generated by Django 5.2.17 on 2026-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
