# Generated by Django 5.2.17 on 2026-10-02 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('service_type', models.CharField(blank=True, default='', max_length=100)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('technician_user_id', models.UUIDField(blank=True, null=True)),
                ('technician_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('amc_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_schedules', to='dms_sales.quotation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='dms_sales.confirmedsite')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('report_code', models.CharField(blank=True, default='', max_length=50)),
                ('service_date', models.DateField()),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('technician_user_id', models.UUIDField(blank=True, null=True)),
                ('technician_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('service_person_name', models.CharField(max_length=255)),
                ('service_person_signature', models.FileField(blank=True, default='', upload_to='reports/signatures/tech/')),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('client_signature', models.FileField(blank=True, default='', upload_to='reports/signatures/client/')),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('AWAITING_CLIENT_SIGN', 'Awaiting Client Signature')], default='PENDING', max_length=30)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports', to='dms_sales.confirmedsite')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='dms_site_services.serviceschedule')),
            ],
        ),
        migrations.CreateModel(
            name='WaterReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('date_tested', models.DateField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hardness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('technician_user_id', models.UUIDField(blank=True, null=True)),
                ('technician_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, default='', upload_to='reports/water/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_reports', to='dms_sales.confirmedsite')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('complainant_user_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('assigned_service_person_name', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_service_person_user_id', models.UUIDField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, default='', upload_to='complaints/')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='dms_sales.confirmedsite')),
            ],
            options={
                'indexes': [models.Index(fields=['unit_id', 'status'], name='dms_site_se_unit_id_fd54e3_idx'), models.Index(fields=['unit_id', 'site_id'], name='dms_site_se_unit_id_92c188_idx'), models.Index(fields=['unit_id', '-created_at'], name='dms_site_se_unit_id_bd135a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('file', models.FileField(upload_to='reports/attachments/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('service_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dms_site_services.servicereport')),
            ],
            options={
                'indexes': [models.Index(fields=['unit_id', 'service_report_id'], name='dms_site_se_unit_id_8d64e9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['unit_id', 'status'], name='dms_site_se_unit_id_f54621_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['unit_id', 'scheduled_date'], name='dms_site_se_unit_id_7584cd_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceschedule',
            index=models.Index(fields=['unit_id', 'site_id'], name='dms_site_se_unit_id_ac7796_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['unit_id', 'status'], name='dms_site_se_unit_id_06ed95_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['unit_id', 'site_id'], name='dms_site_se_unit_id_c5c86b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['unit_id', '-service_date'], name='dms_site_se_unit_id_9feee6_idx'),
        ),
        migrations.AddIndex(
            model_name='waterreport',
            index=models.Index(fields=['unit_id', 'site_id'], name='dms_site_se_unit_id_0f33d4_idx'),
        ),
        migrations.AddIndex(
            model_name='waterreport',
            index=models.Index(fields=['unit_id', '-date_tested'], name='dms_site_se_unit_id_30fab4_idx'),
        ),
    ]
