# Generated by Django 5.2.17 on 2026-10-04 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms_sales', '0002_productcatalog_category'),
        ('dms_site_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteServiceProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by_user_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_id', models.UUIDField(db_index=True)),
                ('dc_number', models.CharField(blank=True, default='', max_length=100)),
                ('service_type', models.CharField(blank=True, default='', max_length=100)),
                ('service_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('last_serviced_date', models.DateField(blank=True, null=True)),
                ('technician_user_id', models.UUIDField(blank=True, null=True)),
                ('technician_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to='dms_sales.confirmedsite')),
            ],
            options={
                'indexes': [models.Index(fields=['unit_id', 'site_id'], name='dms_site_se_unit_id_daf5b4_idx')],
            },
        ),
    ]
