# Generated by Django 5.2.17 on 2026-10-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization'),
        ),
        migrations.AddConstraint(
            model_name='appsubscription',
            constraint=models.UniqueConstraint(fields=('organization', 'app'), name='subscription_unique_org_app'),
        ),
        migrations.AddConstraint(
            model_name='appsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('app', 'admin'), _negated=True), name='subscription_never_administration'),
        ),
    ]
